# Generated by Django 4.0.10 on 2023-07-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('ownership_type', models.CharField(choices=[(0, 'Own'), (1, 'Rent'), (2, 'Temp')], max_length=4)),
                ('approved', models.BooleanField(default=False)),
                ('submited_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(default=None, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_from', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('is_admin_message', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='contractrequests.contractrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('contract_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contractrequests.contractrequest')),
                ('message_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachement', to='contractrequests.message')),
            ],
        ),
    ]
